import type { Metadata } from 'next';
import '@/styles/globals.scss';

import { ColorSchemeScript, DirectionProvider, MantineProvider } from '@mantine/core';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <DirectionProvider>
          <MantineProvider>{children}</MantineProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
