import { PROJECT_STORE_PREFIX } from '@/project-settings/global';

export const THEME_COLOR_SCHEMA_STORE_NAME = `${PROJECT_STORE_PREFIX}THEME_COLOR_SCHEMA`;
export const THEME_LTR_STORE_NAME = `${PROJECT_STORE_PREFIX}THEME_LTR`;
export const THEME_PRIMARY_COLOR_STORE_NAME = `${PROJECT_STORE_PREFIX}THEME_PRIMARY_COLOR`;
