import { PropsWithChildren } from 'react';
import { ColorSchemeScript } from '@mantine/core';
import type { Metadata } from 'next';
import i18nConfig from '@/i18nConfig';
import ManagersServerRegistry from '@/managers/ManagersRegistry';
import { THEME_COLOR_SCHEMA_STORE_NAME } from '@/managers/ThemeManager/def';
import { getThemePersistentStateFromCookies } from '@/managers/ThemeManager/utils';
import '@/styles/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<
  {
    params: { locale: string };
  } & PropsWithChildren
>) {
  const themeConfigFromCookies = getThemePersistentStateFromCookies();

  return (
    <html lang={locale} dir={themeConfigFromCookies.direction}>
      <head>
        <ColorSchemeScript
          defaultColorScheme={themeConfigFromCookies.colorScheme}
          localStorageKey={THEME_COLOR_SCHEMA_STORE_NAME}
        />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
      </head>
      <body>
        <ManagersServerRegistry>{children}</ManagersServerRegistry>
      </body>
    </html>
  );
}
