import i18nConfig from '@/i18nConfig';
import type { Metadata } from 'next';
import '@/styles/globals.scss';

import { ColorSchemeScript } from '@mantine/core';
import { getThemeConfigPersistentStateFromCookies } from '@/managers/ThemeConfigManager/utils';
import { THEME_COLOR_SCHEMA_STORE_NAME } from '@/managers/ThemeConfigManager/def';
import ManagersServerRegistry from '@/managers/ManagersRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const themeConfigFromCookies = getThemeConfigPersistentStateFromCookies();

  return (
    <html lang={locale} dir={themeConfigFromCookies.direction}>
      <head>
        <ColorSchemeScript
          defaultColorScheme={themeConfigFromCookies.colorScheme}
          localStorageKey={THEME_COLOR_SCHEMA_STORE_NAME}
        />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
      </head>
      <body>
        <ManagersServerRegistry>{children}</ManagersServerRegistry>
      </body>
    </html>
  );
}
